<?php
/**
 * Title: tutormatchup - Testimonials
 * Slug: tutormatchup/testimonials
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */

$img_url_1 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-1.jpg' ) ); /* <?php echo esc_url( $img_url_1 ); ?> */
$img_url_2 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-2.jpg' ) ); /* <?php echo esc_url( $img_url_2 ); ?> */
$img_url_3 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-3.jpg' ) ); /* <?php echo esc_url( $img_url_3 ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"rgba(255,248,247,0.65)","bg_gradient":"radial-gradient(rgba(255,255,255,0.97) 0%,rgba(255,255,255,0.99) 100%)","bg_image_xy":{"x":0.12,"y":0.77},"mb_lg":"","pb":"3","pt_lg":"7","pb_lg":"7","position":"position-relative","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(255,248,247,0.65)'  bg_gradient='radial-gradient(rgba(255,255,255,0.97) 0%,rgba(255,255,255,0.99) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb='3'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg=''  pb_lg='7'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pb-3 pt-7 pb-lg-7 bg-image-fixed container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"waves","sd_color":"light","styleid":"block-caga4ioi5i","sd_shortcode":"[bs_shape_divider sd='waves'  sd_position=''  sd_color='light'  sd_custom_color='#0073aa'  sd_width='200'  sd_height='100'  sd_flip='false'  sd_invert='false'  sd_btf='false'  styleid='block-caga4ioi5i' ]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-caga4ioi5i blockstrap-shape blockstrap-shape- position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none"><path class="bg-light blockstrap-shape-fill" d="M421.9,6.5c22.6-2.5,51.5,0.4,75.5,5.3c23.6,4.9,70.9,23.5,100.5,35.7c75.8,32.2,133.7,44.5,192.6,49.7            c23.6,2.1,48.7,3.5,103.4-2.5c54.7-6,106.2-25.6,106.2-25.6V0H0v30.3c0,0,72,32.6,158.4,30.5c39.2-0.7,92.8-6.7,134-22.4            c21.2-8.1,52.2-18.2,79.7-24.2C399.3,7.9,411.6,7.5,421.9,6.5z"/>            </svg></div><style>.block-caga4ioi5i { pointer-events: none;background-repeat: no-repeat;left: -1px;right: -1px;top: -1px;line-height: 0;overflow: hidden;margin: 0 1px;}.block-caga4ioi5i svg{ height: 100px;width: calc(200% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-caga4ioi5i svg path{ }</style>
<!-- /wp:blockstrap/blockstrap-widget-shape-divider -->

<!-- wp:blockstrap/blockstrap-widget-container {"bg_color":"rgba(0,0,0,0.03)","mb_lg":"","pr_lg":"0","pl_lg":"0","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.03)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='0'  pb_lg=''  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 bg-image-fixed container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","text_align_lg":"text-lg-center","mb_lg":"","pb":"0","pb_lg":"4","flex_align_items_lg":"align-items-lg-center","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg='4'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pb-0 pb-lg-4 bg-image-fixed text-center row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_md":"12","col_lg":"7","mr_lg":"auto","mb_lg":"","ml_lg":"auto","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md='12'  col_lg='7'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='auto'  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container me-auto ms-auto col-md-12 col-lg-7 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"What students say","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"display-5","font_weight":"font-weight-bold","text_align_lg":"text-lg-center","mb_lg":"1"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-1 text-center font-weight-bold display-5">What students say</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Real feedback from learners who found the right tutors.","html_tag":"h3","text_color":"gray-dark","font_size":"fs-5","font_weight":"font-weight-normal","mb_lg":""} -->
<h3 class="wp-block-blockstrap-blockstrap-widget-heading text-gray-dark font-weight-normal fs-5">Real feedback from learners who found the right tutors.</h3>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","row_cols_md":"2","row_cols_lg":"3","mb_lg":"","sd_shortcode":"[bs_container container='row'  h100=''  row_cols='1'  row_cols_md='2'  row_cols_lg='3'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container row-cols-1 row-cols-md-2 row-cols-lg-3 bg-image-fixed row"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_md":"4","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md='4'  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-md-4 mb-3 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"transparent","mb_lg":"","pt":"3","pr":"2","pl":"2","pt_lg":"5","pr_lg":"4","pb_lg":"4","pl_lg":"4","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr='2'  pb=''  pl='2'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='4'  pb_lg='4'  pl_lg='4'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-3 pe-2 ps-2 pt-lg-5 pe-lg-4 pb-4 ps-lg-4 border-0 rounded-0 bg-transparent bg-image-fixed card h-100"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","mb_lg":"","pr_lg":"6","pl_lg":"6","border":"0","rounded":"rounded","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='6'  pb_lg=''  pl_lg='6'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-6 ps-6 border-0 bg-image-fixed card-img-top rounded overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_url( $img_url_1 ); ?>","img_aspect":"1by1","font_size":"0","mr_lg":"auto","ml_lg":"auto","img_mask":"circle","css_class":"w-50","content":"\u003cfigure class=\u0022  ratio ratio-1x1  embed-has-action overflow-hidden me-auto mb-3 ms-auto w-50 \u0022 style=\u0022 \u0022\u003e\u003cimg style='-webkit-mask-image: url(\u0022http://tutormatchup.local/wp-content/plugins/blockstrap-page-builder-blocks/assets/masks/circle.svg\u0022);-webkit-mask-size: contain;-webkit-mask-repeat: no-repeat;-webkit-mask-position: center center;' src=\u0022<?php echo esc_url( $img_url_1 ); ?>\u0022 alt=\u0022\u0022 loading=\u0022\u0022 class=\u0022mw-100 w-100 embed-item-cover-xy\u0022  /\u003e\u003c/figure\u003e","sd_shortcode":"[bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_url( $img_url_1 ); ?>'  fallback_img_src=''  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='1by1'  img_cover=''  img_border=''  img_border_width=''  img_border_opacity=''  img_rounded=''  img_rounded_size=''  img_shadow=''  img_overlay=''  text_color=''  font_size='0'  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='auto'  mb_lg='3'  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask='circle'  img_mask_position='center center'  visibility_conditions=''  css_class='w-50' ]"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","text_align_lg":"text-lg-center","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-image-fixed text-center card-body rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"I struggled with calculus until I found my tutor here. His step-by-step explanations made everything click. I finally passed with confidence!","html_tag":"p","text_color":"gray-dark","font_size":"fs-5","font_weight":"font-weight-normal"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-gray-dark font-weight-normal fs-5">I struggled with calculus until I found my tutor here. His step-by-step explanations made everything click. I finally passed with confidence!</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Michael T.","html_tag":"h6","text_color":"primary","font_size":"fs-5","font_weight":"font-weight-bold","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-primary font-weight-bold fs-5">Michael T.</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Engineering Student","html_tag":"div","text_color":"gray-dark","text_color_custom":"#949494","font_size":"fs-6","font_size_custom":0.9,"font_weight":"font-weight-normal","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading text-gray-dark font-weight-normal fs-6">Engineering Student</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","mb_md":"4","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md='4'  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-md-4 mb-3 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"transparent","mb_lg":"","pt":"3","pr":"2","pl":"2","pt_lg":"5","pr_lg":"4","pb_lg":"4","pl_lg":"4","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr='2'  pb=''  pl='2'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='4'  pb_lg='4'  pl_lg='4'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-3 pe-2 ps-2 pt-lg-5 pe-lg-4 pb-4 ps-lg-4 border-0 rounded-0 bg-transparent bg-image-fixed card h-100"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","mb_lg":"","pr_lg":"6","pl_lg":"6","border":"0","rounded_size":"circle","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='6'  pb_lg=''  pl_lg='6'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='circle'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-6 ps-6 border-0 rounded-circle bg-image-fixed card-img-top"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_url( $img_url_2 ); ?>","img_aspect":"1by1","font_size":"0","mr_lg":"auto","ml_lg":"auto","img_mask":"circle","css_class":"w-50","content":"\u003cfigure class=\u0022  ratio ratio-1x1  embed-has-action overflow-hidden me-auto mb-3 ms-auto w-50 \u0022 style=\u0022 \u0022\u003e\u003cimg style='-webkit-mask-image: url(\u0022http://tutormatchup.local/wp-content/plugins/blockstrap-page-builder-blocks/assets/masks/circle.svg\u0022);-webkit-mask-size: contain;-webkit-mask-repeat: no-repeat;-webkit-mask-position: center center;' src=\u0022<?php echo esc_url( $img_url_2 ); ?>\u0022 alt=\u0022\u0022 loading=\u0022\u0022 class=\u0022mw-100 w-100 embed-item-cover-xy\u0022  /\u003e\u003c/figure\u003e","sd_shortcode":"[bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_url( $img_url_2 ); ?>'  fallback_img_src=''  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='1by1'  img_cover=''  img_border=''  img_border_width=''  img_border_opacity=''  img_rounded=''  img_rounded_size=''  img_shadow=''  img_overlay=''  text_color=''  font_size='0'  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='auto'  mb_lg='3'  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask='circle'  img_mask_position='center center'  visibility_conditions=''  css_class='w-50' ]"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","text_align_lg":"text-lg-center","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-image-fixed text-center card-body rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"I love how flexible the lessons are. My tutor adjusts to my schedule, and I’ve already seen huge improvements in my grades.","html_tag":"p","text_color":"gray-dark","font_size":"fs-5","font_weight":"font-weight-normal"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-gray-dark font-weight-normal fs-5">I love how flexible the lessons are. My tutor adjusts to my schedule, and I’ve already seen huge improvements in my grades.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Daniel H.","html_tag":"h6","text_color":"primary","font_size":"fs-5","font_weight":"font-weight-bold","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-primary font-weight-bold fs-5">Daniel H.</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"University Freshman","html_tag":"div","text_color":"gray-dark","text_color_custom":"#949494","font_size":"fs-6","font_size_custom":0.9,"font_weight":"font-weight-normal","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading text-gray-dark font-weight-normal fs-6">University Freshman</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 bg-image-fixed col"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"transparent","mb_lg":"","pt":"3","pr":"2","pl":"2","pt_lg":"5","pr_lg":"4","pb_lg":"4","pl_lg":"4","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='3'  pr='2'  pb=''  pl='2'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg='4'  pb_lg='4'  pl_lg='4'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-3 pe-2 ps-2 pt-lg-5 pe-lg-4 pb-4 ps-lg-4 border-0 rounded-0 bg-transparent bg-image-fixed card h-100"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","mb_lg":"","pr_lg":"6","pl_lg":"6","border":"0","rounded":"rounded","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='6'  pb_lg=''  pl_lg='6'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-6 ps-6 border-0 bg-image-fixed card-img-top rounded overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"url","img_url":"<?php echo esc_url( $img_url_3 ); ?>","img_aspect":"1by1","font_size":"0","mr_lg":"auto","ml_lg":"auto","img_mask":"circle","css_class":"w-50","content":"\u003cfigure class=\u0022  ratio ratio-1x1  embed-has-action overflow-hidden me-auto mb-3 ms-auto w-50 \u0022 style=\u0022 \u0022\u003e\u003cimg style='-webkit-mask-image: url(\u0022http://tutormatchup.local/wp-content/plugins/blockstrap-page-builder-blocks/assets/masks/circle.svg\u0022);-webkit-mask-size: contain;-webkit-mask-repeat: no-repeat;-webkit-mask-position: center center;' src=\u0022<?php echo esc_url( $img_url_3 ); ?>\u0022 alt=\u0022\u0022 loading=\u0022\u0022 class=\u0022mw-100 w-100 embed-item-cover-xy\u0022  /\u003e\u003c/figure\u003e","sd_shortcode":"[bs_image img_src='url'  img_image=''  img_image_id=''  img_size=''  img_url='<?php echo esc_url( $img_url_3 ); ?>'  fallback_img_src=''  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to=''  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='1by1'  img_cover=''  img_border=''  img_border_width=''  img_border_opacity=''  img_rounded=''  img_rounded_size=''  img_shadow=''  img_overlay=''  text_color=''  font_size='0'  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='auto'  mb_lg='3'  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask='circle'  img_mask_position='center center'  visibility_conditions=''  css_class='w-50' ]"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","text_align_lg":"text-lg-center","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-image-fixed text-center card-body rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Thanks to my tutor, my SAT score jumped by 150 points. The personalized approach was exactly what I needed to stay motivated.","html_tag":"p","text_color":"gray-dark","font_size":"fs-5","font_weight":"font-weight-normal"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-gray-dark font-weight-normal fs-5">Thanks to my tutor, my SAT score jumped by 150 points. The personalized approach was exactly what I needed to stay motivated.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Ethan S.","html_tag":"h6","text_color":"primary","font_size":"fs-5","font_weight":"font-weight-bold","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-primary font-weight-bold fs-5">Ethan S.</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"SAT Prep Student","html_tag":"div","text_color":"gray-dark","text_color_custom":"#949494","font_size":"fs-6","font_size_custom":0.9,"font_weight":"font-weight-normal","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading text-gray-dark font-weight-normal fs-6">SAT Prep Student</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->